version: '3.8'

services:

  mongodb:
    container_name: mongodb
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Quanta.123!
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - 27017:27017
    restart: always
    networks:
      - backend

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=Quanta.123!
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=Quanta.123!
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 8089:8081
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge