version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:80"
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
volumes:
  mongodb-data:
    driver: local
