version: '3.8'

services:

  mongodb:
    container_name: mongodb
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - 27017:27017
    restart: always
    networks:
      - backend

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 8089:8081
    networks:
      - backend

  api:
    container_name: api
    image: python:3.9
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && uvicorn api.main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
